### ISSUE TITLE
Python 3.x Support

### ISSUE THREAD

**Issue by yalnazov** [dimagi/jsonobject#107]
Hi, 

are there plans to support Python 3.x in near future?

Best.

**Comment by michaelherold** [comment]
It looks like this was added in #124. This is significant functionality that hasn't been released yet. @dannyroberts could you push a new version soon so those of us who need to support Python 3.x can pull it from PyPI?

**Comment by dannyroberts** [comment]
@michaelherold thanks for the bump, I just pushed it to pypi as version 0.7.0

**Comment by dannyroberts** [comment]
Thanks for your help both of you!
