### ISSUE TITLE
Unable to assign constants (or any non json object properties) to class

### ISSUE THREAD

**Issue by benrudolph** [dimagi/jsonobject#123]
Not sure if this is bug or feature, but I was using this the other day and had something like this:

```
class MyClass(JsonObject)
  name = StringProperty()
  address = StringProperty()
  ....

  PREFIX = "MyRandomPrefix"
```

and this would cause jsonobject to choke

**Comment by dannyroberts** [comment]
Hmm, I'd expect that to add 'PREFIX': 'MyRadomPrefix' to the json output. But I think for what you want you can use `_PREFIX` because properties with an underscore are ignored from json output

**Comment by benrudolph** [comment]
just tried it again and it does seem to work. i think things were getting funky cause i was trying to call PREFIX in the init function. good to know about the `_`
