### ISSUE TITLE
Old version of Cython required in version from pip

### ISSUE THREAD

**Issue by rudykocur** [dimagi/jsonobject#168]
Hello,

We're heavily using windows for development and deployment of our application. Our CI server install packages mainly precompiled for windows (https://www.lfd.uci.edu/~gohlke/pythonlibs/) when there are C extensions needed.

Available Cython version from above page is 0.29.7, but jsonobject installed from pypi repo is hardcoded for 0.27.3 version. Could you bump (or relax) requirements in pypi version to include newer version of Cython? (like you have at master version in repo)

Regards

**Comment by emord** [comment]
@rudykocur just upload 0.9.9 https://pypi.org/project/jsonobject/0.9.9/ Let me know if you have any more issues
