### ISSUE TITLE
Plan to bump version on PyPi to include Python 3.9 support?

### ISSUE THREAD

**Issue by seanmarpo** [dimagi/jsonobject#178]
Hey folks,
Is there a plan to release the latest Python 3.9 compatibility changes via a new version on PyPi?

Thanks!

**Comment by czue** [comment]
I think that's a good idea. @dannyroberts I can do the release if you agree

**Comment by dannyroberts** [comment]
Thanks @czue, yeah go for it!

**Comment by czue** [comment]
all set @seanmarpo  https://pypi.org/project/jsonobject/ (version `0.9.10`)

**Comment by seanmarpo** [comment]
@czue / @dannyroberts, appreciate it! Thanks.
