### ISSUE TITLE
Python 3.12 compatibility

### ISSUE THREAD

**Issue by tammyalexandra** [dimagi/jsonobject#218]
I'm not able to install the latest version of jsonobject (2.1.0) under Python 3.12 (and Poetry 1.7.1):  `ERROR: Could not build wheels for jsonobject, which is required to install pyproject.toml-based projects`.  Are you able to update this package to build under Python 3.12?  Thanks so much!

**Comment by tammyalexandra** [comment]
Pls merge this :-) https://github.com/dimagi/jsonobject/pull/219

**Comment by tammyalexandra** [comment]
Hi @dannyroberts, is it possible to merge in #219 in order to add Python 3.12 support?  Thanks for your help!

**Comment by nickbaum** [comment]
@gherceg You can mark this as fixed too 🙌🏻

**Comment by tammyalexandra** [comment]
Thank you, @nickbaum, @dannyroberts, @gherceg!

**Comment by gherceg** [comment]
Resolved in https://github.com/dimagi/jsonobject/pull/227
